spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

openweathermap:
  key: ${OPENWEATHERMAP_KEY}